<?php

return array(
    'start' => 'Играть в Telegram',
    'start-android' => 'Играть на Android',
    'quick-start' => 'Краткое руководство',
    'public-formulas' => 'Примеры Формул',
    'privacy-policy' => 'Политика конфиденциальности',
    'faq' => 'Вопросы и ответы',
    'purpose' => 'Суть игры',
    'formula' => '"Формула"',
    'review' => 'Просмотр "Формулы"',
    'forgot' => 'Забыл просмотреть',
    'difficulty' => 'Частота просмотра',
    'pause' => 'Пауза от игры',
    'formula-formatting' => 'Форматирование "Формулы"',
    'controls' => 'Доступные команды',
    'name' => 'Почему "MindWarrior"?',
    'formula-example' => '"Формулы" других игроков',
    'share' => 'Поделиться "Формулой"?',
    'privacy' => 'Конфиденциальность "Формулы"',
    'tos' => 'Условия использования',
    'privacy-policy' => 'Политика конфиденциальности',
    'important' => 'Важно',
);
