<?php

return array(
    'start' => 'Auf Telegram spielen',
    'start-android' => 'Auf Android spielen',
    'quick-start' => 'Kurzanleitung',
    'public-formulas' => 'Öffentliche "Formeln"',
    'privacy-policy' => 'Datenschutzrichtlinie',
    'faq' => 'FAQ',
    'purpose' => 'Worum geht es hier?',
    'formula' => '"Formel"',
    'review' => '"Formel" bewerten',
    'forgot' => 'Bewertung vergessen',
    'difficulty' => 'Bewertungshäufigkeit',
    'pause' => 'Spiel pausieren',
    'formula-formatting' => '"Formel"-Formatierung',
    'controls' => 'Befehle',
    'name' => 'Warum "MindWarrior"?',
    'formula-example' => '"Formeln" anderer',
    'share' => '"Formel" teilen',
    'privacy' => 'Datenschutz',
    'tos' => 'Nutzungsbedingungen',
    'privacy-policy' => 'Datenschutzerklärung',
    'important' => 'Wichtig',
);
